---
srl_nokia-interfaces:interface:
# az1 leaves
  - name: ethernet-1/3
    admin-state: enable
    description: "CORE: cr2_e1/1..az1lf1_e-1/55"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.20{core}{next_avail_lower}/30
            - ip-prefix: 169.254.202.1/30
  - name: ethernet-1/4
    admin-state: enable
    description: "CORE: cr2_e1/2..az1lf2_e-1/55"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.20{core}{next_avail_lower}/30
            - ip-prefix: 169.254.202.5/30
  - name: ethernet-1/5
    admin-state: enable
    description: "CORE: cr2_e1/3..az1lf3_e-1/55"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.20{core}{next_avail_lower}/30
            - ip-prefix: 169.254.202.9/30
  - name: ethernet-1/6
    admin-state: enable
    description: "CORE: cr2_e1/4..az1lf4_e-1/55"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.20{core}{next_avail_lower}/30
            - ip-prefix: 169.254.202.13/30
  - name: ethernet-1/7
    admin-state: enable
    description: "CORE: cr2_e1/5..az1lf5_e-1/55"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.20{core}{next_avail_lower}/30
            - ip-prefix: 169.254.202.17/30
  - name: ethernet-1/8
    admin-state: enable
    description: "CORE: cr2_e1/8..az1lf6_e-1/55"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.20{core}.{next_avail_lower}/30
            - ip-prefix: 169.254.202.21/30
# Edge
  - name: ethernet-1/10
    admin-state: enable
    description: "EDGE: cr2_e1/10..ed1_eth2"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.21{core}.{next_avail_lower}/30
            - ip-prefix: 169.254.212.1/30
  - name: ethernet-1/11
    admin-state: enable
    description: "EDGE: cr2_e1/11..ed2_eth2"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.200.{next_avail_lower}/30
            - ip-prefix: 169.254.212.5/30
