---
srl_nokia-interfaces:interface:
# az1 leaves
  # - name: ethernet-1/3
  #   admin-state: enable
  #   description: "CORE: cr01_e1/1..az1lf1_e-1/57"
  #   subinterface:
  #     - index: 0
  #       ipv4:
  #         address:
  #           # 169.254.20{core}{next_avail_lower}/30
  #           - ip-prefix: 169.254.201.1/30
  # - name: ethernet-1/4
  #   admin-state: enable
  #   description: "CORE: cr1_e1/2..az1lf2_e-1/57"
  #   subinterface:
  #     - index: 0
  #       ipv4:
  #         address:
  #           # 169.254.20{core}{next_avail_lower}/30
  #           - ip-prefix: 169.254.201.5/30
  # - name: ethernet-1/5
  #   admin-state: enable
  #   description: "CORE: cr1_e1/3..az1lf3_e-1/57"
  #   subinterface:
  #     - index: 0
  #       ipv4:
  #         address:
  #           # 169.254.20{core}{next_avail_lower}/30
  #           - ip-prefix: 169.254.201.9/30
  # - name: ethernet-1/6
  #   admin-state: enable
  #   description: "CORE: cr1_e1/4..az1lf4_e-1/57"
  #   subinterface:
  #     - index: 0
  #       ipv4:
  #         address:
  #           # 169.254.20{core}{next_avail_lower}/30
  #           - ip-prefix: 169.254.201.13/30
  # - name: ethernet-1/7
  #   admin-state: enable
  #   description: "CORE: az1cr1_e1/5..az1lf5_e-1/57"
  #   subinterface:
  #     - index: 0
  #       ipv4:
  #         address:
  #           # 169.254.20{core}{next_avail_lower}/30
  #           - ip-prefix: 169.254.201.17/30
  # - name: ethernet-1/8
  #   admin-state: enable
  #   description: "CORE: cr1_e1/8..az1lf6_e-1/57"
  #   subinterface:
  #     - index: 0
  #       ipv4:
  #         address:
  #           # 169.254.20{core}.{next_avail_lower}/30
  #           - ip-prefix: 169.254.201.21/30
# Edge
  - name: ethernet-1/10
    admin-state: enable
    description: "EDGE: cr1_e1/10..ed1_eth3"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.21{core}.{next_avail_lower}/30
            - ip-prefix: 169.254.213.1/30
  - name: ethernet-1/11
    admin-state: enable
    description: "EDGE: cr1_e1/11..ed2_eth3"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.200.{next_avail_lower}/30
            - ip-prefix: 169.254.213.5/30
  - name: system0
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{devnum}.{254_lf|255_sp}/32
            - ip-prefix: 169.254.3.253/32
srl_nokia-network-instance:network-instance:
  - name: WAN_EDGE
    admin-state: enable
    interface:
      - name: ethernet-1/10.0
      - name: ethernet-1/11.0
      - name: system0.0
    protocols:
      srl_nokia-bgp:bgp:
        autonomous-system: 65999
        router-id: 169.254.1.253
        ipv4-unicast:
          admin-state: enable
          multipath:
            max-paths-level-1: 8
            max-paths-level-2: 8
        group:
          - group-name: ebgp_edge
            admin-state: enable
            export-policy: ebgp_export_edge
            import-policy: ebgp_import_edge
            graceful-restart:
              admin-state: enable
            trace-options:
              flag:
                - name: events
                - name: graceful-restart
            timers:
              connect-retry: 1
              hold-time: 9
              keepalive-interval: 3
              minimum-advertisement-interval: 1
        neighbor:
          - peer-address: 169.254.213.2
            peer-as: 62371
            peer-group: ebgp_edge
          - peer-address: 169.254.213.6
            peer-as: 62371
            peer-group: ebgp_edge
srl_nokia-routing-policy:routing-policy:
  prefix-set:
    - name: WAN_EDGE_loopbacks
      prefix:
        - ip-prefix: "169.254.1.253/32"
          mask-length-range: "32..32"
        - ip-prefix: "169.254.2.253/32"
          mask-length-range: "32..32"
        - ip-prefix: "169.254.3.253/32"
          mask-length-range: "32..32"
        - ip-prefix: "169.254.1.252/32"
          mask-length-range: "32..32"
        - ip-prefix: "169.254.2.252/32"
          mask-length-range: "32..32"
    - name: default_route
      prefix:
        - ip-prefix: "0.0.0.0/0"
          mask-length-range: "32..32"
    - name: proton_public
      prefix:
        - ip-prefix: "185.70.40.0/22"
          mask-length-range: "32..32"
  policy:
    - name: ebgp_import_edge
      statement:
        - sequence-id: 410
          match:
            prefix-set: WAN_EDGE_loopbacks
            family:
              - ipv4-unicast
          action:
            policy-result: accept
        - sequence-id: 420
          match:
            prefix-set: default_route
            family:
              - ipv4-unicast
          action:
            policy-result: accept
        - sequence-id: 1000
          action:
            policy-result: reject
    - name: ebgp_export_edge
      statement:
        - sequence-id: 410
          match:
            prefix-set: proton_public
            protocol: local
            family:
              - ipv4-unicast
          action:
            policy-result: accept
        - sequence-id: 420
          match:
            prefix-set: proton_public
            protocol: bgp
            family:
              - ipv4-unicast
          action:
            policy-result: accept
        - sequence-id: 430
          match:
            prefix-set: proton_public
            protocol: bgp-evpn
            family:
              - ipv4-unicast
          action:
            policy-result: accept
        - sequence-id: 1000
          action:
            policy-result: reject
