---
srl_nokia-interfaces:interface:
  - name: lag1
    admin-state: enable
    description: "SRV: cab1-srv1_eth1"
    vlan-tagging: true
    subinterface:
      - index: 0
        type: bridged
        admin-state: disable
        vlan: 
          encap: 
            untagged: {}
      - index: 200
        type: bridged
        admin-state: enable
        vlan:
          encap:
            single-tagged: 
              vlan-id: 200
    lag: 
      lag-type: lacp
      #member-speed: 10G
    
  - name: ethernet-1/1
    admin-state: enable
    description: "SRV: cab1-srv1_bond0"
    ethernet: 
      aggregate-id: lag1
      reload-delay: 20
        # ipv4:
        #   address:
        #     # 10.{pod}.{leaf}.{nextfree}/30
        #     - ip-prefix: 10.1.1.1/30
        # ipv6:
        #   address:
        #     # fd00:{pod}{leaf}::{port}:{vrf}:1/64
        #     - ip-prefix: fd00:11::1:100:1/64
  - name: ethernet-1/2
    admin-state: enable
    description: "SRV: cab1-srv2_eth1"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 10.{pod}.{leaf}.{nextfree}/30
            - ip-prefix: 10.1.1.5/30
        ipv6:
          address:
            # fd00:{pod}{leaf}::{port}:{vrf}:1/64
            - ip-prefix: fd00:11::2:100:1/64
  #- name: ethernet-1/3
  #  admin-state: enable
  #  description: "SRV: server3_eth1"
  #  subinterface:
  #    - index: 0
  #      ipv4:
  #        address:
  #          # 10.{pod}.{leaf}.{nextfree}/30
  #          - ip-prefix: 10.1.1.9/30
  #      ipv6:
  #        address:
  #          # fd00:{pod}{leaf}::{port}:{vrf}:1/64
  #          - ip-prefix: fd00:11::3:100:1/64
  # SPACE FOR MORE SERVERS
  # 
  # SPINES!
  - name: ethernet-1/49
    admin-state: enable
    description: "CORE: az1sp01_e1/1..az1lf01_e-1/49"
    subinterface:
      - index: 0
        ipv4: 
          address:
            # 169.254.{spine}{next_avail_upper}/30
            - ip-prefix: 169.254.1.2/30
  - name: ethernet-1/50
    admin-state: enable
    description: "CORE: az1sp02_e1/1..az1lf01_e-1/50"
    subinterface:
      - index: 0
        ipv4: 
          address: 
            # 169.254.{spine}{next_avail_upper}/30
            - ip-prefix: 169.254.2.2/30
  - name: ethernet-1/51
    admin-state: enable
    description: "CORE: az1sp03_e1/1..az1lf01_e-1/51"
    subinterface:
      - index: 0
        ipv4: 
          address: 
            # 169.254.{spine}{next_avail_upper}/30
            - ip-prefix: 169.254.3.2/30
  - name: system0
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          address:
          # 169.254.{devnum}.{254_lf|255_sp}/32
            - ip-prefix: 169.254.1.254/32
  - interface: irb1
    admin-state: enable
    subinterface:
      - index: 1
        ipv4:
          address:
            - ip-prefix: 192.168.0.6/29 
              anycast-gw: true
          arp: 
            learn-unsolicited: true
            evpn: 
              advertise:
                - route-type: dynamic
        anycast-gw: {}
      - index: 200
        ipv4:
          address:
            - ip-prefix: 10.200.200.1/24
              anycast-gw: true
          arp: 
            learn-unsolicited: true
            evpn: 
              advertise:
                - route-type: dynamic
        anycast-gw: {}

srl_nokia-tunnel-interface:tunnel-interface:
  - name: vxlan1
    vxlan-interface: 
    # vlan1 l2vni
    - index: 1
      type: bridged
      ingress:
        vni: 1 
    # vlan1 l3vni
    - index: 10001
      type: bridged
      ingress:
        vni: 10001
    # vlan200 l2vni
    - index: 200
      type: bridged
      ingress:
        vni: 200
    # vlan200 l3vni
    - index: 10200
      type: bridged
      ingress:
        vni: 10200

srl_nokia-system-network-instance:network-instance:
  protocols:
    evpn:
      ethernet-segments:
        bgp-instance:
          - id: 1 
            ethernet-segment:
              - name: cab1-srv1_bond0
                admin-state: enable
                esi: 00:12:12:12:12:12:12:00:00:01
                interface: 
                  - ethernet-interface: lag1
    bgp-vpn:
      bgp-instance:
        - id: 1

srl_nokia-network-instance:network-instance:
  - name: default
    admin-state: enable
    interface:
      - name: ethernet-1/49.0
      - name: ethernet-1/50.0
      - name: ethernet-1/51.0
      - name: system0.0
    protocols:  
      srl_nokia-bgp:bgp:
        autonomous-system: 65001
        router-id: 169.254.1.254
        failure-detection: 
          fast-failover: true
        ipv4-unicast: 
          admin-state: enable
          multipath: 
            max-paths-level-1: 8
            max-paths-level-2: 8
        group:
          - group-name: underlay
            peer-as: 65000
            admin-state: enable
            export-policy: underlay-loopback-out
            import-policy: underlay-loopback-in
            graceful-restart:
              admin-state: enable
            trace-options:
              flag:
                - name: events
                - name: graceful-restart
          - group-name: overlay-fabric
            peer-as: 64999
            local-as: 
              - as-number: 64999
            transport: 
              local-address: 169.254.1.254
            admin-state: enable
            evpn: 
              admin-state: enable
        neighbor:
          - peer-address: 169.254.1.1
            peer-group: underlay
          - peer-address: 169.254.2.1
            peer-group: underlay
          - peer-address: 169.254.3.1
            peer-group: underlay
          - peer-address: 169.254.1.255
            peer-group: overlay-fabric
          - peer-address: 169.254.2.255
            peer-group: overlay-fabric
          - peer-address: 169.254.3.255
            peer-group: overlay-fabric
  # vlan 1 bridge domain
  - name: mac-vrf-1
    type: mac-vrf
    admin-state: enable
    interface:
      - name: ethernet-1/1.0
      - name: irb1.1
    vxlan-interface:
      - name: vxlan1.1
    protocols:
      bgp-evpn:
        bgp-instance: 
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.1
            evi: 1
            ecmp: 3
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:1
              import-rt: target:1:1
  # vlan 1 routing domain
  - name: ip-vrf-1
    type: ip-vrf
    admin-state: enable
    interface:
      - name: irb1.1
    vxlan-interface:
      - name: vxlan1.10001
    protocols:
      bgp-evpn:
        bgp-instance: 
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.10001
            evi: 10001
            ecmp: 3
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:10001
              import-rt: target:1:10001
  # vlan 200 bridge domain
  - name: mac-vrf-200
    type: mac-vrf
    admin-state: enable
    interface:
      - name: ethernet-1/1.200
      - name: irb1.200
    vxlan-interface:
      - name: vxlan1.10200
    protocols:
      bgp-evpn:
        bgp-instance: 
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.200
            evi: 200
            ecmp: 3
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:200
              import-rt: target:1:200
  # vlan 200 routing domain
  - name: ip-vrf-200
    type: ip-vrf
    admin-state: enable
    interface:
      - name: irb1.200
    vxlan-interface:
      - name: vxlan1.10200
    protocols:
      bgp-evpn:
        bgp-instance: 
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.10200
            evi: 10200
            ecmp: 3
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:10200
              import-rt: target:1:10200

srl_nokia-routing-policy:routing-policy:
  prefix-set:
    - name: underlay-loopback-v4
      prefix:
        - ip-prefix: "169.254.0.0/16"
          mask-length-range: "32..32"
  policy:
    - name: underlay-loopback-out
      statement: 
        - sequence-id: 410
          match: 
            prefix-set: underlay-loopback-v4
            protocol: local
            family: 
              - ipv4-unicast
          action: 
            policy-result: accept
        - sequence-id: 420
          match: 
            prefix-set: underlay-loopback-v4
            protocol: bgp
            family: 
              - ipv4-unicast
          action: 
            policy-result: reject
        - sequence-id: 1000
          action: 
            policy-result: reject
    - name: underlay-loopback-in
      statement:
        - sequence-id: 410
          match: 
            prefix-set: underlay-loopback-v4
            protocol: bgp
            family: 
              - ipv4-unicast
          action: 
            policy-result: accept
        - sequence-id: 420
          match: 
            prefix-set: underlay-loopback-v4
            protocol: local
            family: 
              - ipv4-unicast
          action: 
            policy-result: reject
        - sequence-id: 1000
          action: 
            policy-result: reject
