---
srl_nokia-interfaces:interface:
  - name: ethernet-1/1
    admin-state: enable
    description: "SRV: cab3-srv1_eth2"
    vlan-tagging: true
    subinterface:
      - index: 0
        type: bridged
        admin-state: disable
        vlan: 
          encap: 
            untagged: {}
        # ipv4:
        #   address:
        #     # 10.{pod}.{leaf}.{nextfree}/30
        #     - ip-prefix: 10.1.6.1/30
        # ipv6:
        #   address:
        #     # fd00:{pod}{leaf}::{port}:{vrf}:1/64
        #     - ip-prefix: fd00:16::1:100:1/64
  - name: ethernet-1/2
    admin-state: enable
    description: "SRV: cab3-srv2_eth2"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 10.{pod}.{leaf}.{nextfree}/30
            - ip-prefix: 10.1.6.5/30
        ipv6:
          address:
            # fd00:{pod}{leaf}::{port}:{vrf}:1/64
            - ip-prefix: fd00:16::2:100:1/64
  #- name: ethernet-1/3
  #  admin-state: enable
  #  description: "SRV: server3_eth2"
  #  subinterface:
  #    - index: 0
  #      ipv4:
  #        address:
  #          # 10.{pod}.{leaf}.{nextfree}/30
  #          - ip-prefix: 10.1.6.9/30
  #      ipv6:
  #        address:
  #          # fd00:{pod}{leaf}::{port}:{vrf}:1/64
  #          - ip-prefix: fd00:16::3:100:1/64
  # SPACE FOR MORE SERVERS
  # 
  # SPINES!
  - name: ethernet-1/49
    admin-state: enable
    description: "CORE: az1sp01_e1/6..az1lf06_e-1/49"
    subinterface:
      - index: 0
        ipv4:
          # 169.254.{spine}{next_avail_upper}/30
          - address: 169.254.1.22/30
        # ipv6:
        #   address:
        #     # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{0|1}/127
        #     - ip-prefix: fccf:116::6:49:0/127
  - name: ethernet-1/50
    admin-state: enable
    description: "CORE: az1sp02_e1/6..az1lf06_e-1/50"
    subinterface:
      - index: 0
        ipv4:
          # 169.254.{spine}{next_avail_upper}/30
          - address: 169.254.2.22/30
        # ipv6:
        #   address:
        #     # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{0|1}/127
        #     - ip-prefix: fccf:126::6:50:0/127
  - name: ethernet-1/51
    admin-state: enable
    description: "CORE: az1sp03_e1/6..az1lf06_e-1/51"
    subinterface:
      - index: 0
        ipv4:
          # 169.254.{spine}{next_avail_upper}/30
          - address: 169.254.3.22/30
        # ipv6:
        #   address:
        #     # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{0|1}/127
        #     - ip-prefix: fccf:136::6:51:0/127
  - name: system0
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{devnum}.{254_lf|255_sp}/32
            - ip-prefix: 169.254.6.254/32
        # ipv6:
        #   address:
        #     # fded:127::{pod}:{devnum}:{255sp|254lf}
        #     - ip-prefix: fded:127::1:6:254/128

srl_nokia-tunnel-interface:tunnel-interface:
  - name: vxlan1
    vxlan-interface: 
    - index: 1
      type: bridged
      ingress:
        vni: 1
srl_nokia-network-instance:network-instance:
  - name: default
    admin-state: enable
    interface:
      - name: ethernet-1/49.0
      - name: ethernet-1/50.0
      - name: ethernet-1/51.0
      - name: system0.0
    protocols:
      srl_nokia-bgp:bgp:
        autonomous-system: 65006
        router-id: 169.254.6.254
        failure-detection: 
          fast-failover: true
        ipv6-unicast: 
          admin-state: enable
          multipath: 
            max-paths-level-1: 8
            max-paths-level-2: 8
        group:
          - group-name: underlay
            peer-as: 65000
            admin-state: enable
            export-policy: underlay-loopback-out
            import-policy: underlay-loopback-in
            graceful-restart:
              admin-state: enable
            trace-options:
              flag:
                - name: events
                - name: graceful-restart
          - group-name: overlay-fabric
            peer-as: 64999
            local-as: 
              - as-number: 64999
            admin-state: enable
            transport: 
              local-address: fded:127::1:6:254
            evpn: 
              admin-state: enable
        neighbor:
          - peer-address: fccf:116::6:49:1
            peer-group: underlay
          - peer-address: fccf:126::6:50:1
            peer-group: underlay
          - peer-address: fccf:136::6:51:1
            peer-group: underlay
          - peer-address: fded:127::1:1:255
            peer-group: overlay-fabric
          - peer-address: fded:127::1:2:255
            peer-group: overlay-fabric
          - peer-address: fded:127::1:3:255
            peer-group: overlay-fabric
  - name: vrf-1
    type: mac-vrf
    admin-state: enable
    interface:
      - name: ethernet-1/1.0
    vxlan-interface:
      - name: vxlan1.1
    protocols:
      bgp-evpn:
        bgp-instance: 
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.1
            evi: 111
            ecmp: 3
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:111
              import-rt: target:1:111
srl_nokia-routing-policy:routing-policy:
  prefix-set:
    - name: underlay-loopback-v4
      prefix:
        - ip-prefix: "169.254.0.0/16"
          mask-length-range: "32..32"
    - name: underlay-loopback-v6
      prefix:
        - ip-prefix: "fded:127::/32"
          mask-length-range: "128..128"
  policy:
    - name: underlay-loopback-out
      statement: 
        - sequence-id: 410
          match: 
            prefix-set: underlay-loopback-v4
            protocol: local
            family: 
              - ipv4-unicast
          action: 
            policy-result: accept
        - sequence-id: 420
          match: 
            prefix-set: underlay-loopback-v4
            protocol: bgp
            family: 
              - ipv4-unicast
          action: 
            policy-result: reject
        - sequence-id: 610
          match: 
            prefix-set: underlay-loopback-v6
            protocol: local
            family: 
              - ipv6-unicast
          action: 
            policy-result: accept
        - sequence-id: 620
          match: 
            prefix-set: underlay-loopback-v6
            protocol: bgp
            family: 
              - ipv6-unicast
          action: 
            policy-result: reject
        - sequence-id: 1000
          action: 
            policy-result: reject
    - name: underlay-loopback-in
      statement:
        - sequence-id: 410
          match: 
            prefix-set: underlay-loopback-v4
            protocol: bgp
            family: 
              - ipv4-unicast
          action: 
            policy-result: accept
        - sequence-id: 420
          match: 
            prefix-set: underlay-loopback-v4
            protocol: local
            family: 
              - ipv4-unicast
          action: 
            policy-result: reject
        - sequence-id: 610
          match: 
            prefix-set: underlay-loopback-v6
            protocol: bgp
            family: 
              - ipv6-unicast
          action: 
            policy-result: accept
        - sequence-id: 620
          match: 
            prefix-set: underlay-loopback-v6
            protocol: local
            family: 
              - ipv6-unicast
          action: 
            policy-result: reject
        - sequence-id: 1000
          action: 
            policy-result: reject
