---
srl_nokia-interfaces:interface:
  - name: ethernet-1/1
    admin-state: enable
    description: "SRV: cab2-srv1_eth1"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 10.{pod}.{leaf}.{nextfree}/30
            - ip-prefix: 10.1.3.1/30
        ipv6:
          address:
            # fd00:{pod}{leaf}::{port}:{vrf}:1/64
            - ip-prefix: fd00:13::1:100:1/64
  - name: ethernet-1/2
    admin-state: enable
    description: "SRV: cab2-srv2_eth1"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 10.{pod}.{leaf}.{nextfree}/30
            - ip-prefix: 10.1.3.5/30
        ipv6:
          address:
            # fd00:{pod}{leaf}::{port}:{vrf}:1/64
            - ip-prefix: fd00:13::2:100:1/64
  #- name: ethernet-1/3
  #  admin-state: enable
  #  description: "SRV: server3_eth1"
  #  subinterface:
  #    - index: 0
  #      ipv4:
  #        address:
  #          # 10.{pod}.{leaf}.{nextfree}/30
  #          - ip-prefix: 10.1.1.9/30
  #      ipv6:
  #        address:
  #          # fd00:{pod}{leaf}::{port}:{vrf}:1/64
  #          - ip-prefix: fd00:11::3:100:1/64
  # SPACE FOR MORE SERVERS
  # 
  # SPINES!
  - name: ethernet-1/49
    admin-state: enable
    description: "CORE: az1sp01_e1/3..az1lf03_e-1/49"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}.{nextfree}/31
            - ip-prefix: 169.254.1.4/31
        ipv6:
          address:
            # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{0|1}/127
            - ip-prefix: fccf:113::3:49:0/127
  - name: ethernet-1/50
    admin-state: enable
    description: "CORE: az1sp02_e1/3..az1lf03_e-1/50"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}.{nextfree}/31
            - ip-prefix: 169.254.2.4/31
        ipv6:
          address:
            # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{0|1}/127
            - ip-prefix: fccf:123::3:50:0/127
  - name: ethernet-1/51
    admin-state: enable
    description: "CORE: az1sp03_e1/3..az1lf03_e-1/51"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}.{nextfree}/31
            - ip-prefix: 169.254.3.4/31
        ipv6:
          address:
            # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{0|1}/127
            - ip-prefix: fccf:133::3:51:0/127
  - name: system0
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          address:
            - ip-prefix: 169.254.3.254/32
        ipv6:
          address:
            - ip-prefix: fded:127::3:254/128

srl_nokia-network-instance:network-instance:
  - name: default
    admin-state: enable
    interface:
      - name: ethernet-1/49.0
      - name: ethernet-1/50.0
      - name: ethernet-1/51.0
      - name: system0.0
    protocols:
      srl_nokia-bgp:bgp:
        autonomous-system: 65002
        router-id: 169.254.3.254
        group:
          - group-name: underlay
            peer-as: 65000
            admin-state: enable
            export-policy: underlay-loopback
            import-policy: underlay-loopback
        neighbor:
          - peer-address: fccf:113::3:49:1
            peer-group: underlay
          - peer-address: fccf:123::3:50:1
            peer-group: underlay
          - peer-address: fccf:133::3:51:1
            peer-group: underlay
#  - name: default
#    admin-state: enable
#    interface:
#      - name: ethernet-1/1.0
#      - name: ethernet-1/2.0
#      - name: ethernet-1/3.0
#    protocols:
#      srl_nokia-bgp:bgp:
#        autonomous-system: 65999
#        router-id: 169.254.1.255
#        group:
#          - group-name: overlay
#            peer-as: 65999
#            admin-state: enable
#        neighbor:
#          - peer-address: lol
#            peer-group: underlay
srl_nokia-routing-policy:routing-policy:
  prefix-set:
    - name: underlay-loopback-v4
      prefix:
        - ip-prefix: "169.254.254.0/23"
          mask-length-range: "32..32"
    - name: underlay-loopback-v6
      prefix:
        - ip-prefix: "fded:127::/32"
          mask-length-range: "128..128"
  policy:
    - name: underlay-loopback
      statement: 
        - sequence-id: 10
          match: 
            prefix-set: underlay-loopback-v4
            family: 
              - ipv4-unicast
          action: 
            policy-result: accept
        - sequence-id: 20
          match: 
            prefix-set: underlay-loopback-v6
            family: 
              - ipv6-unicast
          action: 
            policy-result: accept
        - sequence-id: 1000
          action: 
            policy-result: reject
