---
srl_nokia-interfaces:interface:
  - name: ethernet-1/1
    admin-state: enable
    description: "CORE: az1sp01_e1/1..az1lf02_e-1/49"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}.{nextfree}/31
            - ip-prefix: 169.254.1.1/31
        ipv6:
          address:
            # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{0|1}/127
            - ip-prefix: fccf:111::1:49:1/127
  - name: ethernet-1/2
    admin-state: enable
    description: "CORE: az1sp01_e1/2..az1lf02_e-1/49"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}.{nextfree}/31
            - ip-prefix: 169.254.1.3/31
        ipv6:
          address:
            # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{0|1}/127
            - ip-prefix: fccf:112::2:49:1/127
  - name: ethernet-1/3
    admin-state: enable
    description: "CORE: az1sp01_e1/3..az1lf03_e-1/49"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}.{nextfree}/31
            - ip-prefix: 169.254.1.5/31
        ipv6:
          address:
            # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{0|1}/127
            - ip-prefix: fccf:113::3:49:1/127
  - name: ethernet-1/4
    admin-state: enable
    description: "CORE: az1sp01_e1/4..az1lf04_e-1/49"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}.{nextfree}/31
            - ip-prefix: 169.254.1.7/31
        ipv6:
          address:
            # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{0|1}/127
            - ip-prefix: fccf:114::4:49:1/127
  - name: ethernet-1/5
    admin-state: enable
    description: "CORE: az1sp01_e1/5..az1lf05_e-1/49"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}.{nextfree}/31
            - ip-prefix: 169.254.1.9/31
        ipv6:
          address:
            # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{0|1}/127
            - ip-prefix: fccf:115::5:49:1/127
  - name: ethernet-1/6
    admin-state: enable
    description: "CORE: az1sp01_e1/6..az1lf06_e-1/49"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}.{nextfree}/31
            - ip-prefix: 169.254.1.11/31
        ipv6:
          address:
            # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{0|1}/127
            - ip-prefix: fccf:116::6:49:1/127
  - name: system0
    admin-state: enable
    subinterface:
      - index: 0
        # ipv4:
        #   address:
        #     - ip-prefix: 169.254.1.255/32
        ipv6:
          address:
            # fded:127::{pod}:{devnum}:{255sp|254lf}
            - ip-prefix: fded:127::1:1:255/128

srl_nokia-network-instance:network-instance:
  - name: default
    admin-state: enable
    interface:
      - name: ethernet-1/1.0
      - name: ethernet-1/2.0
      - name: ethernet-1/3.0
      - name: ethernet-1/4.0
      - name: ethernet-1/5.0
      - name: ethernet-1/6.0
      - name: system0.0
    protocols:
      srl_nokia-bgp:bgp:
        autonomous-system: 65000
        router-id: 169.254.1.255
        ipv6-unicast: 
          admin-state: enable
          multipath: 
            max-paths-level-1: 3
        group:
          - group-name: underlay
            admin-state: enable
            export-policy: underlay-loopback-out
            import-policy: underlay-loopback-in
            graceful-restart:
              admin-state: enable
            trace-options:
              flag:
                - name: events
                - name: graceful-restart
        neighbor:
          - peer-address: fccf:111::1:49:0
            peer-as: 65001
            peer-group: underlay
          - peer-address: fccf:112::2:49:0
            peer-as: 65001
            peer-group: underlay
          - peer-address: fccf:113::3:49:0
            peer-as: 65002
            peer-group: underlay
          - peer-address: fccf:114::4:49:0
            peer-as: 65002
            peer-group: underlay
          - peer-address: fccf:115::5:49:0
            peer-as: 65003
            peer-group: underlay
          - peer-address: fccf:116::6:49:0
            peer-as: 65003
            peer-group: underlay
srl_nokia-routing-policy:routing-policy:
  prefix-set:
    # - name: underlay-loopback-v4
    #   prefix: 
    #     - ip-prefix: "169.254.0.0/16"
    #       mask-length-range: "32..32"
    - name: underlay-loopback-v6
      prefix: 
        - ip-prefix: fded:127::/32
          mask-length-range: "128..128"
  policy:
    - name: underlay-loopback-out
      statement: 
        - sequence-id: 10
          match: 
            prefix-set: underlay-loopback-v6
            protocol: local
            family: 
              - ipv6-unicast
          action: 
            policy-result: accept
        - sequence-id: 20
          match:
            prefix-set: underlay-loopback-v6
            protocol: bgp
            bgp: 
              as-path-length:
                value: 1
            family: 
              - ipv6-unicast
          action: 
            policy-result: accept
        - sequence-id: 1000
          action: 
            policy-result: reject
    - name: underlay-loopback-in
      statement: 
        - sequence-id: 10
          match: 
            prefix-set: underlay-loopback-v6
            protocol: bgp
            family: 
              - ipv6-unicast
          action: 
            policy-result: accept
        - sequence-id: 20
          match: 
            prefix-set: underlay-loopback-v6
            protocol: local
            family: 
              - ipv6-unicast
          action: 
            policy-result: reject
        - sequence-id: 1000
          action: 
            policy-result: reject
