---
srl_nokia-interfaces:interface:
  - name: ethernet-1/1
    admin-state: enable
    description: "CORE: az1sp02_e1/1..az1lf02_e-1/50"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}.{nextfree}/31
            - ip-prefix: 169.254.2.1/31
        ipv6:
          address:
            # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{1|2}/127
            - ip-prefix: fccf:121::1:50:1/127
  - name: ethernet-1/2
    admin-state: enable
    description: "CORE: az1sp02_e1/2..az1lf02_e-1/50"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}.{nextfree}/31
            - ip-prefix: 169.254.2.3/31
        ipv6:
          address:
            # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{1|2}/127
            - ip-prefix: fccf:122::2:50:1/127
  - name: ethernet-1/3
    admin-state: enable
    description: "CORE: az1sp02_e1/3..az1lf03_e-1/50"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}.{nextfree}/31
            - ip-prefix: 169.254.2.5/31
        ipv6:
          address:
            # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{1|2}/127
            - ip-prefix: fccf:123::3:50:1/127
  - name: ethernet-1/4
    admin-state: enable
    description: "CORE: az1sp02_e1/4..az1lf04_e-1/50"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}.{nextfree}/31
            - ip-prefix: 169.254.2.7/31
        ipv6:
          address:
            # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{1|2}/127
            - ip-prefix: fccf:124::4:50:1/127
  - name: ethernet-1/5
    admin-state: enable
    description: "CORE: az1sp02_e1/5..az1lf05_e-1/50"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}.{nextfree}/31
            - ip-prefix: 169.254.2.9/31
        ipv6:
          address:
            # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{1|2}/127
            - ip-prefix: fccf:125::5:50:1/127
  - name: ethernet-1/6
    admin-state: enable
    description: "CORE: az1sp02_e1/6..az1lf06_e-1/50"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}.{nextfree}/31
            - ip-prefix: 169.254.2.11/31
        ipv6:
          address:
            # fccf:{pod}{spine}{leaf}::{spine-port}:{leaf-port}:{1|2}/127
            - ip-prefix: fccf:126::6:50:1/127
  - name: system0
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          address:
            - ip-prefix: 169.254.2.255/32
        ipv6:
          address:
            - ip-prefix: fded:127::2:255/128

srl_nokia-network-instance:network-instance:
  - name: default
    admin-state: enable
    interface:
      - name: ethernet-1/1.0
      - name: ethernet-1/2.0
      - name: ethernet-1/3.0
      - name: ethernet-1/4.0
      - name: ethernet-1/5.0
      - name: ethernet-1/6.0
      - name: system0.0
    protocols:
      srl_nokia-bgp:bgp:
        autonomous-system: 65000
        router-id: 169.254.2.255
        group:
          - group-name: underlay
            admin-state: enable
            export-policy: underlay-loopback
            import-policy: underlay-loopback
        neighbor:
          - peer-address: fccf:121::1:50:0
            peer-as: 65001
            peer-group: underlay
          - peer-address: fccf:122::2:50:0
            peer-as: 65001
            peer-group: underlay
          - peer-address: fccf:123::3:50:0
            peer-as: 65002
            peer-group: underlay
          - peer-address: fccf:124::4:50:0
            peer-as: 65002
            peer-group: underlay
          - peer-address: fccf:125::5:50:0
            peer-as: 65003
            peer-group: underlay
          - peer-address: fccf:126::6:50:0
            peer-as: 65003
            peer-group: underlay
srl_nokia-routing-policy:routing-policy:
  prefix-set:
    - name: underlay-loopback-v4
      prefix:
        - ip-prefix: "169.254.254.0/23"
          mask-length-range: "32..32"
    - name: underlay-loopback-v6
      prefix:
        - ip-prefix: "fded:127::/32"
          mask-length-range: "128..128"
  policy:
    - name: underlay-loopback
      statement: 
        - sequence-id: 10
          match: 
            prefix-set: underlay-loopback-v4
            family: 
              - ipv4-unicast
          action: 
            policy-result: accept
        - sequence-id: 20
          match: 
            prefix-set: underlay-loopback-v6
            family: 
              - ipv6-unicast
          action: 
            policy-result: accept
        - sequence-id: 1000
          action: 
            policy-result: reject
